import { PrescriptionAnalysis } from "./types";

export const generateBuyLinks = (medicineName: string) => {
  const encoded = encodeURIComponent(medicineName);
  return [
    {
      platform: "Tata 1mg" as const,
      url: `https://www.1mg.com/search/all?name=${encoded}`,
    },
    {
      platform: "PharmEasy" as const,
      url: `https://pharmeasy.in/search/all?name=${encoded}`,
    },
    {
      platform: "Apollo Pharmacy" as const,
      url: `https://www.apollopharmacy.in/search-medicines/${encoded}`,
    },
    {
      platform: "Netmeds" as const,
      url: `https://www.netmeds.com/catalogsearch/result?q=${encoded}`,
    },
  ];
};

export const samplePrescriptions: Record<string, PrescriptionAnalysis> = {
  demo1: {
    submissionId: "demo-rx-001",
    status: "completed",
    createdAt: new Date().toISOString(),
    doctorDetails: {
      name: "Dr. Rajesh Sharma, MD",
      qualification: "Senior Physician (Internal Medicine)",
      clinic: "City Healthcare Clinic, New Delhi",
      date: "18 Sep 2026",
      patientName: "Rahul Verma (Age: 34)",
    },
    safetyNotes: [
      "Finish the complete 5-day course of antibiotics even if feeling better.",
      "Take Pantoprazole on an empty stomach in the morning 30 mins before breakfast.",
    ],
    medicines: [
      {
        id: "med-1",
        name: "Amoxicillin 500mg",
        genericName: "Amoxicillin Trihydrate",
        dosage: "500 mg Capsule",
        frequency: "3 times a day",
        duration: "5 days",
        timing: {
          morning: true,
          afternoon: true,
          night: true,
          timingNote: "Take after meals with a full glass of water",
        },
        doctorInstructions: "Take 1 capsule every 8 hours after food. Do not skip doses.",
        purpose: "Antibiotic for bacterial respiratory infection",
        isAvailable: true,
        buyLinks: generateBuyLinks("Amoxicillin 500mg"),
        alternatives: [
          {
            id: "alt-1a",
            name: "Novamox 500 Capsule",
            type: "Substitute Brand",
            manufacturer: "Cipla Ltd",
            composition: "Amoxicillin 500mg",
            priceEstimate: "₹68 for 10 capsules",
            description: "Identical active composition. Top tier trusted Indian manufacturer.",
            buyLinks: generateBuyLinks("Novamox 500 Capsule"),
          },
          {
            id: "alt-1b",
            name: "Mox 500 Capsule",
            type: "Substitute Brand",
            manufacturer: "Sun Pharma",
            composition: "Amoxicillin 500mg",
            priceEstimate: "₹72 for 10 capsules",
            description: "High quality bio-equivalent substitute.",
            buyLinks: generateBuyLinks("Mox 500 Capsule"),
          },
          {
            id: "alt-1c",
            name: "Generic Amoxicillin 500mg",
            type: "Generic Equivalent",
            manufacturer: "Jan Aushadhi / Generic Labs",
            composition: "Amoxicillin 500mg",
            priceEstimate: "₹22 for 10 capsules",
            description: "Government generic equivalent at fraction of brand cost.",
            buyLinks: generateBuyLinks("Amoxicillin 500mg Generic"),
          },
        ],
      },
      {
        id: "med-2",
        name: "Dolo 650mg",
        genericName: "Paracetamol / Acetaminophen",
        dosage: "650 mg Tablet",
        frequency: "As needed (Max 3 times daily)",
        duration: "3 - 5 days",
        timing: {
          morning: true,
          afternoon: true,
          night: true,
          timingNote: "Take only if temperature > 100°F or body ache persists",
        },
        doctorInstructions: "Take 1 tablet after food when fever or pain is felt. Minimum 6 hours gap between tablets.",
        purpose: "Fever reducer and pain reliever",
        isAvailable: true,
        buyLinks: generateBuyLinks("Dolo 650mg"),
        alternatives: [
          {
            id: "alt-2a",
            name: "Calpol 650mg Tablet",
            type: "Substitute Brand",
            manufacturer: "GSK Pharmaceuticals",
            composition: "Paracetamol 650mg",
            priceEstimate: "₹32 for 15 tablets",
            description: "Widely available direct replacement.",
            buyLinks: generateBuyLinks("Calpol 650mg"),
          },
          {
            id: "alt-2b",
            name: "Pacimol 650mg Tablet",
            type: "Substitute Brand",
            manufacturer: "IPCA Laboratories",
            composition: "Paracetamol 650mg",
            priceEstimate: "₹28 for 15 tablets",
            description: "Equal potency pain and fever relief.",
            buyLinks: generateBuyLinks("Pacimol 650mg"),
          },
        ],
      },
      {
        id: "med-3",
        name: "Pan 40mg Tablet",
        genericName: "Pantoprazole Sodium",
        dosage: "40 mg Tablet",
        frequency: "Once daily",
        duration: "7 days",
        timing: {
          morning: true,
          afternoon: false,
          night: false,
          timingNote: "Before breakfast (Empty Stomach)",
        },
        doctorInstructions: "Swallow whole 30 minutes before morning tea/breakfast to prevent acidity from antibiotics.",
        purpose: "Gastric acid reducer / Stomach protection",
        isAvailable: true,
        buyLinks: generateBuyLinks("Pan 40mg Tablet"),
        alternatives: [
          {
            id: "alt-3a",
            name: "Pantocid 40mg Tablet",
            type: "Substitute Brand",
            manufacturer: "Sun Pharma",
            composition: "Pantoprazole 40mg",
            priceEstimate: "₹145 for 15 tablets",
            description: "Direct equivalent acid suppressant.",
            buyLinks: generateBuyLinks("Pantocid 40mg"),
          },
          {
            id: "alt-3b",
            name: "Pansec 40mg Tablet",
            type: "Substitute Brand",
            manufacturer: "Cipla Ltd",
            composition: "Pantoprazole 40mg",
            priceEstimate: "₹120 for 15 tablets",
            description: "Equal strength acid relief.",
            buyLinks: generateBuyLinks("Pansec 40mg"),
          },
        ],
      },
    ],
  },
  demo2: {
    submissionId: "demo-rx-002",
    status: "completed",
    createdAt: new Date().toISOString(),
    doctorDetails: {
      name: "Dr. Ananya Deshmukh, DM (Cardiology)",
      qualification: "Consultant Cardiologist & Diabetologist",
      clinic: "Apex Heart & Diabetes Center, Mumbai",
      date: "19 Sep 2026",
      patientName: "Mrs. Sunita Patel (Age: 58)",
    },
    safetyNotes: [
      "Do not stop blood pressure medication abruptly.",
      "Monitor blood glucose levels every fortnight.",
    ],
    medicines: [
      {
        id: "med-4",
        name: "Glycomet SR 500mg",
        genericName: "Metformin Hydrochloride (Sustained Release)",
        dosage: "500 mg Tablet",
        frequency: "Twice daily",
        duration: "Continuous",
        timing: {
          morning: true,
          afternoon: false,
          night: true,
          timingNote: "Immediately after breakfast and dinner",
        },
        doctorInstructions: "Take 1 tablet after morning breakfast and 1 after night dinner. Do not crush or chew sustained-release tablet.",
        purpose: "Type 2 Diabetes Blood Sugar Control",
        isAvailable: true,
        buyLinks: generateBuyLinks("Glycomet SR 500mg"),
        alternatives: [
          {
            id: "alt-4a",
            name: "Metfor SR 500mg",
            type: "Substitute Brand",
            manufacturer: "Cipla Ltd",
            composition: "Metformin SR 500mg",
            priceEstimate: "₹42 for 15 tablets",
            description: "Sustained release Metformin equivalent.",
            buyLinks: generateBuyLinks("Metfor SR 500mg"),
          },
          {
            id: "alt-4b",
            name: "Obimet 500 SR",
            type: "Substitute Brand",
            manufacturer: "Abbott",
            composition: "Metformin SR 500mg",
            priceEstimate: "₹48 for 15 tablets",
            description: "High quality diabetes control substitute.",
            buyLinks: generateBuyLinks("Obimet 500 SR"),
          },
        ],
      },
      {
        id: "med-5",
        name: "Telma 40mg Tablet",
        genericName: "Telmisartan",
        dosage: "40 mg Tablet",
        frequency: "Once daily",
        duration: "Continuous",
        timing: {
          morning: true,
          afternoon: false,
          night: false,
          timingNote: "Fixed time every morning",
        },
        doctorInstructions: "Take 1 tablet in the morning at 8:00 AM with water. Check BP weekly.",
        purpose: "Hypertension / High Blood Pressure Control",
        isAvailable: true,
        buyLinks: generateBuyLinks("Telma 40mg Tablet"),
        alternatives: [
          {
            id: "alt-5a",
            name: "Telmikind 40mg",
            type: "Substitute Brand",
            manufacturer: "Mankind Pharma",
            composition: "Telmisartan 40mg",
            priceEstimate: "₹55 for 15 tablets",
            description: "Direct brand replacement for blood pressure management.",
            buyLinks: generateBuyLinks("Telmikind 40mg"),
          },
          {
            id: "alt-5b",
            name: "Telsartan 40mg",
            type: "Substitute Brand",
            manufacturer: "Dr Reddy's Laboratories",
            composition: "Telmisartan 40mg",
            priceEstimate: "₹62 for 15 tablets",
            description: "Equivalent BP regulator.",
            buyLinks: generateBuyLinks("Telsartan 40mg"),
          },
        ],
      },
    ],
  },
};
